#!/bin/bash

### Affichage de toute les instances avec leur version de CiviCRM
function old_vcv() {
  
  listSite=$(plesk bin site --list)
  echo "+-------------------------------------+-------------+--------------+---------+"
  echo "| Instance                            | CMS         | CiviCRM      | PHP     |"
  echo "+-------------------------------------+-------------+--------------+---------+"
  
  for instance_wp in $listSite; do
    versionCIVI_WP=$(grep "define('CIVICRM_PLUGIN_VERSION'" $racine/$instance_wp/httpdocs/wp-content/plugins/civicrm/civicrm.php 2>/dev/null | awk -F"'" '{print $4}')
    
    if [ -f $racine/$instance_wp/.php-version ]; then
      versionPHP_WP=$(cat $racine/$instance_wp/.php-version 2>/dev/null)
    else
      versionPHP_WP="Unknown"
    fi
    
    if [ -f "$racine/$instance_wp/httpdocs/wp-content/uploads/civicrm/civicrm.settings.php" ]; then
      printf "| %-35s | %-11s | %-12s | %-7s |\n" "$instance_wp" "Wordpress" "$versionCIVI_WP" "$versionPHP_WP"
    fi
  done
    
  for instance_drupal in $listSite; do
    versionCIVI_DRUPAL=$(grep '<version_no>' $racine/$instance_drupal/httpdocs/sites/all/modules/civicrm/xml/version.xml 2>/dev/null | awk -F">" '{print $2}' | awk -F"<" '{print $1}') 
      
    if [ -f $racine/$instance_drupal/.php-version ]; then
      versionPHP_DRUPAL=$(cat $racine/$instance_drupal/.php-version 2>/dev/null)
    else
      versionPHP_DRUPAL="Unknown"
    fi
      
    if [ -f "$racine/$instance_drupal/httpdocs/sites/default/civicrm.settings.php" ]; then
      printf "| %-35s | %-11s | %-12s | %-7s |\n" "$instance_drupal" "Drupal" "$versionCIVI_DRUPAL" "$versionPHP_DRUPAL"
    fi
  done  

  for instance_standalone in $listSite; do
    versionCIVI_STANDALONE=$(grep '<version_no>' $racine/$instance_standalone/httpdocs/core/xml/version.xml 2>/dev/null | awk -F">" '{print $2}' | awk -F"<" '{print $1}') 
      
    if [ -f $racine/$instance_standalone/.php-version ]; then
      versionPHP_STANDALONE=$(cat $racine/$instance_standalone/.php-version 2>/dev/null)
    else
      versionPHP_STANDALONE="Unknown"
    fi
      
    if [ -f "$racine/$instance_standalone/httpdocs/private/civicrm.settings.php" ]; then
      printf "| %-35s | %-11s | %-12s | %-7s |\n" "$instance_standalone" "Standalone" "$versionCIVI_STANDALONE" "$versionPHP_STANDALONE"
    fi
  done

  echo "+-------------------------------------+-------------+--------------+---------+"
}

old_vcv $@