#!/bin/bash
##
## Développé par Renaud Fradin, Fawzy Elsam et Ilias Assadki
##
#############################################################
##
##  Clonage d'instances
##
#############################################################

vhosts="/var/www/vhosts" ; mysql_server="localhost:3306"

GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[1;37m'
NC='\033[0m' # No color

source functions.sh 
cd $vhosts
 
## Choix de l'instance source 
echo -e '\e[93m=============================================\033[0m'
echo "Choisissez l'instance source que vous souhaitez cloner ?" ; echo " "
 
# Récupération de la liste des domaines 
listSite=($(plesk bin site --list))
select folder_source in "${listSite[@]}";
	do 
    echo -e '\e[93m=============================================\033[0m'
		echo -e "L'instance source choisie est : ${GREEN}$folder_source${NC}" ; echo " "
		sleep 0.6
    break;
done

# Affectation de variables selon le CMS de l'instance source
test -e $vhosts/$folder_source/httpdocs/wp-config.php && cms_instance_source="wordpress"
test -e $vhosts/$folder_source/httpdocs/sites/default/settings.php && cms_instance_source="drupal"
test -e $vhosts/$folder_source/httpdocs/private/civicrm.settings.php && cms_instance_source="standalone"

# Affichage en tableau de la/les base.s de données de $folder_source (instance source)
plesk db "SELECT d.name AS 'Domaine source', db.name AS 'BDD source', du.login AS 'Utilisateur de la BDD' FROM data_bases db JOIN domains d ON db.dom_id = d.id JOIN clients c ON d.cl_id = c.id JOIN db_users du ON db.id = du.db_id WHERE d.name='$folder_source';"

# Récupération des idenfifiants de l'instance source
if [ "$cms_instance_source" == "wordpress" ]; then 
    getWordpressID_Source
fi

if [ "$cms_instance_source" == "drupal" ]; then
    getDrupalID_Source
fi

if [ "$cms_instance_source" == "standalone" ]; then
    getStandaloneID_Source
fi

# # Point de contrôle de vérification ou non de l'égalité de l'utilisateur et la base de données source 
# if [ "$mysql_source_user" == "$mysql_source_database" ]; then
# 	echo " " ; echo -e ">> [${RED}ERREUR${NC}] Le nom de la BDD source ainsi que son nom d'utilisateur sont similaires, changez les identifiants de $folder_source depuis Plesk" ; echo " "
#     exit 1
# fi

## Choix de l'instance destination
echo -e '\e[93m=============================================\033[0m'
sleep 0.8
echo "Choisissez l'instance de destination ?" ; echo " "

# Récupération de la liste des domaines 
listSite=($(plesk bin site --list))
select folder_destination in "${listSite[@]}";
	do 
      echo -e '\e[93m=============================================\033[0m'
	  echo -e "L'instance de destination choisie est : ${GREEN}$folder_destination${NC}" ; echo " "
    break;
done

# Affectation de variables selon le CMS de l'instance destination
test -e $vhosts/$folder_destination/httpdocs/wp-config.php && cms_instance_destination="wordpress"
test -e $vhosts/$folder_destination/httpdocs/sites/default/settings.php && cms_instance_destination="drupal"
test -e $vhosts/$folder_destination/httpdocs/private/civicrm.settings.php && cms_instance_destination="standalone"

# Point de contrôle de vérification de $folder_source == $folder_destination 
if [ "$folder_source" == "$folder_destination" ]
	then
		echo " " ; echo -e ">> [${RED}ERREUR${NC}] Les instances source et destination sont similaires, restaurer $folder_source et/ou $folder_destination" ; echo " "
    exit 1
fi

# Affichage en tableau de la/les base.s de données de $folder_destination (instance destination)
plesk db "SELECT d.name AS 'Domaine destination', db.name AS 'BDD destination', du.login AS 'Utilisateur de la BDD' FROM data_bases db JOIN domains d ON db.dom_id = d.id JOIN clients c ON d.cl_id = c.id JOIN db_users du ON db.id = du.db_id WHERE d.name='$folder_destination';"

# Récupération des idenfifiants de l'instance destination
if [ "$cms_instance_destination" == "wordpress" ]; then 
    getWordpressID_Destination
fi

if [ "$cms_instance_destination" == "drupal" ]; then
    getDrupalID_Destination
fi

if [ "$cms_instance_destination" == "standalone" ]; then
    getStandaloneID_Destination
fi


# Point de contrôle de vérification ou non de l'égalité de l'utilisateur et la base de données destination 
if [ "$mysql_destination_user" == "$mysql_destination_database" ]; then
	echo " " ; echo -e ">> [${RED}ERREUR${NC}] Le nom de la BDD destination ainsi que son nom d'utilisateur sont similaires, changez les identifiants de $folder_destination depuis Plesk" ; echo " "
    exit 0
fi

# Point de contrôle de vérification ou non de l'égalité de l'utilisateur et la base de données destination
if [ "$mysql_source_user" == "$mysql_destination_user" ] || [ "$mysql_source_database" == "$mysql_destination_database" ]; then
	echo " " ; echo -e ">> [${RED}ERREUR${NC}] Les identifiants des domaines source et destination sont similaires, restaurer $folder_source et/ou $folder_destination"	; echo " "
	exit 0
fi 

echo -e '\e[93m===============================================\033[0m' 
echo -e "Vous allez cloner ${GREEN}$folder_source${NC} vers ${GREEN}$folder_destination${NC}"	
echo -e '\e[93m================================================\033[0m' 

echo " "

# Condition pour suppression des tables de la base de données destination
echo -e "Faut-il vider la base de données ${GREEN}$mysql_destination_database${NC} de ${GREEN}$folder_destination${NC} ? o(oui) ou n(non)"
read reponse1
if test "$reponse1" = "o"
	then
		sleep 0.6 && vidageBDD_Destination && echo " "
		sleep 0.6 && dbSize_Source && dbSize_Destination && echo " "
	else
    echo "> Démarrage du clonage"  
fi

echo -e '\e[93m================================================\033[0m' ; echo " "

#***  Début clonage des fichiers de l'instance ***#
## Partie source

cd $vhosts/$folder_source/httpdocs

if [[ ! -d "temp_clonage" ]]; then
		mkdir temp_clonage && cd temp_clonage
else 
		cd temp_clonage 
fi

cd $vhosts/$folder_source

echo "> Début de l'archivage"
tar -cf - httpdocs | pv -s $(du -sb httpdocs | awk '{print $1}') > "$folder_source.tar.gz" 

echo " "
mv $folder_source.tar.gz $vhosts/$folder_destination

## Partie destination
cd $vhosts/$folder_destination

## Mise en maintenance de $folder_destination
## Fin de la mise en maintenance

rm -rf httpdocs

echo "> Début du désarchivage"
pv -s $(du -sb "$folder_source.tar.gz" | awk '{print $1}') "$folder_source.tar.gz" | tar -xvf - -C $vhosts/$folder_destination > /dev/null 

rm $folder_source.tar.gz && echo " "
echo -e '\e[93m================================================\033[0m' ; echo " "

cd $vhosts/$folder_destination/httpdocs/temp_clonage 

# Modification des URLs dans la base de données des occurences de $folder_source vers $folder_destination 
exportBDD_Source # Création du fichier .sql source
remplacementURL_BDD
nettoyageAdressesElectroniques
importBDD_Destination # Import du fichier .sql source dans la base de données destination, après modifications

echo "Rebuilding the triggers..."; 
cd $vhosts/$folder_destination/httpdocs
cv api System.flush triggers=1 > /dev/null

cd $vhosts/$folder_destination

echo -e ">> Modification des valeurs des fichiers de configuration ..."


# Modification des variables dans les fichiers de configuration (Conditions sur le CMS)
# Wordpress
while [ "$cms_instance_source" == "wordpress" ] && ([[ "$folder_source" != "parlemonde.org" || "$folder_source" != "familles.sandbox.parlemonde.org" || "$folder_source" != "prof.sandbox.parlemonde.org" || "$folder_source" != "mediateurs.sandbox.parlemonde.org" || "$folder_source" != "sandbox.parlemonde.org" ]])
	do 
		echo -e ">> CMS : Wordpress"	
		majValeurs_Wordpress
   
		if test -e $vhosts/$folder_destination/httpdocs/.user.ini 
			then
				majValeurs_Wordfence 
			else
			  echo -e ">> Fichiers générés par WordFence absents"	
		fi

		if test -e $vhosts/$folder_destination/httpdocs/wp-content/uploads/civicrm/civicrm.settings.php
			then
				majValeursCivicrm_Wordpress
			else 
			  echo -e ">> CiviCRM pour Wordpress absent des extensions"	
		fi
  break
done

# Wordpress et instance Parlemonde
while [ "$cms_instance_source" == "wordpress" ] && ([[ "$folder_source" == "parlemonde.org" || "$folder_source" == "familles.sandbox.parlemonde.org" || "$folder_source" == "prof.sandbox.parlemonde.org" || "$folder_source" == "mediateurs.sandbox.parlemonde.org" || "$folder_source" == "sandbox.parlemonde.org" ]])
  do 
		echo -e ">> CMS : Wordpress & instance Parlemonde"	
		majValeurs_Wordpress

		if test -e $vhosts/$folder_destination/httpdocs/.user.ini 
			then
				majValeurs_Wordfence 
			else
			  echo -e ">> Fichiers générés par WordFence absents"	
		fi
  break
done

while [ "$cms_instance_source" == "drupal" ] 
	do
		echo -e ">> CMS : Drupal"	
		majValeurs_Drupal 

		if test -e $vhosts/$folder_destination/httpdocs/sites/default/civicrm.settings.php
			then
				majValeursCivicrm_Drupal
			else
				echo -e ">> CiviCRM pour Drupal absent"	
		fi
  break
done

# Standalone >> à ajouter

# Nettoyage des repertoire source et destination
cd $vhosts/$folder_source/httpdocs && echo -e ">> Suppression du dossier temp_clonage source..." && rm -rf temp_clonage && cd $vhosts 
cd $vhosts/$folder_destination/httpdocs && echo -e ">> Suppression du dossier temp_clonage destination..." && rm -rf temp_clonage && cd $vhosts && echo " "
echo -e '\e[93m================================================\033[0m' ; echo " "

# Correction de la propriété des fichiers 
echo -e ">> Plesk repair..." && echo " " && plesk repair fs `echo $folder_destination` -y && echo " "

# # Point de contrôle de vérification ou non de l'égalité de l'utilisateur et la base de données destination
# if [ "$mysql_source_user" == "$mysql_destination_user" ] || [ "$mysql_source_database" == "$mysql_destination_database" ]
# 	then
# 		echo " " ; echo -e ">> [${RED}ERREUR${NC}] Les identifiants des domaines source et destination sont similaires, veuillez restaurer $folder_source et/ou $folder_destination" ; echo " "
# 		exit 0
# fi

[ $cms_instance_source == "wordpress" ] && echo -e ">> PENSER À VÉRIFIER LES FICHIERS WP-CONFIG.PHP AINSI QUE LE CIVICRM.SETTINGS.PHP" && echo " "
[ $cms_instance_source == "drupal" ] && echo -e ">> PENSER À VÉRIFIER SETTINGS.PHP AINSI QUE LE CIVICRM.SETTINGS.PHP" && echo " "

echo " " ; echo -e ">> Site ${GREEN}$folder_source${NC} bien cloné vers ${GREEN}$folder_destination${NC}" ; echo " " ; 
echo -e ">> Penser à reconstruire les triggers CiviCRM via ${GREEN}cvff${NC} dans le dossier de l'instance" ; echo " " ; # ne s'affiche pas pour l'instant
cd $vhosts