#!/bin/bash
source "/$CUSTOM_DIR/sources/utils.sh"
source "/$CUSTOM_DIR/sources/cv_source.sh"

### Aliases pour git clone de l'extension de CiviCRM et activation //experimental >> à simplifier
function cvgc() {
    instance=$(getplesksite) 
    testCMS
    echo "$cms_instance"
    local path_ext=""

    if [ "$cms_instance" == "wordpress" ]; then 
        path_ext=$racine/$instance/httpdocs/wp-content/uploads/civicrm/ext
    fi
    if [ "$cms_instance" == "drupal" ]; then
        path_ext=$racine/$instance/httpdocs/sites/default/files/civicrm/ext
    fi
    if [ "$cms_instance" == "standalone" ]; then
        path_ext=$racine/$instance/httpdocs/ext
    fi
    if [ "$cms_instance" == "backdrop" ]; then
    	path_ext=$racine/$instance/httpdocs/files/civicrm/ext
    fi

    cd "$path_ext"

    input="$1"
    extension="${input##*/}"
    extension="${extension%.git}"
    if [ -d "$extension" ]; then
        echo -e "${YELLOW}[ATTENTION]${NC} L'extension semble déjà être présente dans : $path_ext";
        echo -e "${BLUE}[ INFO ]${NC} Vous pouvez la mettre à jour directement via la commande ${PURPLE}cvgp${NC} !";
        return 1;
    fi
    git clone "$1"

    #cd "$extension" # cd vers le dossier de l'extension installée selon le nom déconstruit ! intérêt ?
    extracted_string=$(echo "$extension" | awk -F '.' '{print $NF}') && echo "Nom de l'extension clonée : $extracted_string"
    ##cv ext:enable "$extracted_string" && cv ext:upgrade-db && rep
    cv en "$extension" && cv updb && rep
    echo -e "L'extension \033[32m$extension\033[0m a été installée"
    rep
}

cvgc $@
