#!/bin/bash

source "/$CUSTOM_DIR/sources/utils.sh"
source "/$CUSTOM_DIR/sources/cv_source.sh"

### Aliases pour git pull de l'extension de CiviCRM et activation
## condition drupal à gérer
function cvgp() {
	test -d httpdocs && cd httpdocs
    instance=$(getplesksite)
    extension=$(echo "$1" | awk -F'/' '{print $NF}' | sed 's/\.git$//') # récupère ce qu'il y'a avant le .git
    testCMS

    if [ "$cms_instance" == "wordpress" ]; then 
        cd $racine/$instance/wp-content/uploads/civicrm/ext/$extension && git pull "$1"
        #cv en "$extension" && cv updb && rep
    fi

    if [ "$cms_instance" == "drupal" ]; then
        cd $racine/$instance/sites/default/files/civicrm/ext/$extension && git pull "$1"
        #cv en "$extension" && cv updb && rep
    fi

    if [ "$cms_instance" == "standalone" ]; then
        cd $racine/$instance/ext/$extension && git pull "$1"
        #cv en "$extension" && cv updb && rep
    fi

    if [ "$cms_instance" == "backdrop" ]; then
    	cd $racine/$instance/files/civicrm/ext && git pull "$1"    	    	
    fi
    echo -e "L'extension \033[32m$extension\033[0m a été mise à jour"
    rep
}

cvgp $@
