#!/bin/bash

source $CUSTOM_DIR/includes/clone_functions_utils.sh
source $CUSTOM_DIR/includes/functions.sh

# folder_source=$(pwd | sed -E 's|/var/www/vhosts/([^/]+)/httpdocs.*|\1|')

path=$(pwd)
subscription=$(echo "$path" | cut -d'/' -f5)
second=$(echo "$path" | cut -d'/' -f6)

if [ "$second" = "httpdocs" ]; then
    folder_source="$subscription"
else
    folder_source="$second"
fi

echo $folder_source

result="$(get_instance_cms $folder_source)" || exit 1
read cms_instance_source mysql_source_database mysql_source_user mysql_source_mdp <<< "$result"
print_clone_bdd_resume "BDD du site sélectionné" "$mysql_source_database" "$mysql_source_user" "$mysql_source_mdp"
