#!/bin/bash

source "$CUSTOM_DIR/sources/utils.sh"
source "$CUSTOM_DIR/includes/functions.sh";

site=$(getplesksite)
path=$(get_site_root $site)
cd $racine
cd $path

if [ ! -e ./nextcloud/config/config.php ]; then
	echo config.php not found at $(pwd)/nextcloud/config/config.php
	exit 1
fi

owner_user=$(stat -c %U ./nextcloud/config/config.php || exit 1)
php_version='8.3'

# sudo -u $owner_user /opt/plesk/php/$php_version/bin/php -i | grep "\.ini"

sudo -u $owner_user /opt/plesk/php/$php_version/bin/php ./nextcloud/occ "$@"
