#!/bin/bash

source "$CUSTOM_DIR/includes/functions.sh"

main() {
    echo "TEst"
    echo "CUSTOM_DIR = $CUSTOM_DIR"

    # echo -e '\e[93m=============================================\033[0m'
    # echo "Choisissez l'instance à mettre à jour parmi les domaines disponibles : "
    # listSite=($(getcvsites | sort))
    # select instance in "${listSite[@]}"; do break; done
    # [ -z "$instance" ] && echo -e "${RED}[ ERREUR ]${NC} Instance invalide" && exit 1


    # # Tester recalculer_serialisation
    # recalculer_serialisation "/var/www/vhosts/vps1.gestad.net/20260227091059_vps1_gestad_net.sql"
    # local my_common="${CUSTOM_DIR%/scripts_server}"
    # echo "my_common = $my_common"

    # local mysql_source_database="$my_common/TMP/civicrm_setting"
    # echo "mysql_source_database = $mysql_source_database"

    # recalculer_serialisation "$mysql_source_database.sql"


    # # Tester sur une ligne isolée
    # echo 's:462:\"https://syntec.civicrm.makoa.net/civicrm/contact/view/participant?id=67886&amp;cid=35684\";' | python3 -c "
    # import re, sys

    # content = sys.stdin.read()

    # def fix_length_escaped(match):
    #     str_value = match.group(1)
    #     correct_length = len(str_value.encode('utf-8'))
    #     print(f'DEBUG: longueur calculée = {correct_length}', file=sys.stderr)
    #     print(f'DEBUG: longueur réelle chaîne = {len(str_value)}', file=sys.stderr)
    #     return 's:' + str(correct_length) + ':\\\\\"' + str_value + '\\\\\";'

    # pattern_escaped = re.compile(r's:\d+:\\\\\"([^\\\\\"]*?)\\\\\";', re.DOTALL)
    # result = pattern_escaped.sub(fix_length_escaped, content)
    # print(result)
    # "
}

main