#!/bin/bash
##
## Développé par Renaud Fradin, Fawzy Elsam
## et Ilias Assadki
##
################################################
##
##  Scripts de mise a jour de CiviCRM pour les instances web
##
################################################
shopt -s expand_aliases
######################################################

# Security check
# if [ ! -f ~/.bashrc ]; then
#     printf -- '\033[41m  .bashrc must exist. abord. \033[0m\n'
#     exit 1
# fi

vhosts="/var/www/vhosts"

source $CUSTOM_DIR/includes/functions_civicrm.sh
source $CUSTOM_DIR/includes/functions.sh

echo -e '\e[93m=============================================\033[0m'
echo "Choisissez l'instance à mettre à jour parmi les domaines disponibles : "
listSite=($(plesk bin site --list))
select instance in "${listSite[@]}"; do break; done
[ -z "$instance" ] && echo -e "${RED}[ ERREUR ]${NC} Instance invalid" && exit 1

echo -e '\e[93m=============================================\033[0m'
echo -e "L'instance cible choisie est : ${GREEN}$instance${NC}"
civi_folder=$instance

test -e $vhosts/$civi_folder/httpdocs/sites/default/settings.php && cms_instance="drupal"
test -e $vhosts/$civi_folder/httpdocs/private/civicrm.settings.php && cms_instance="standalone"
test -e $vhosts/$civi_folder/httpdocs/wp-config.php && cms_instance="wordpress"

chemin_plugins_drupal="$vhosts/$civi_folder/httpdocs/sites/all/modules"  
chemin_plugins_wordpress="$vhosts/$civi_folder/httpdocs/wp-content/plugins"  
chemin_plugins_standalone="$vhosts/$civi_folder/httpdocs"   

if [ ! -e $chemin_plugins_wordpress ] && [ ! -e $chemin_plugins_drupal ] && [ ! -e $chemin_plugins_standalone ]; then
    echo -e '\e[93m=======================================\033[0m' 
    echo -e "${RED}[ ERREUR ]${NC} Aucun CMS valide sélectionné"
    echo -e '\e[93m=======================================\033[0m'   
    exit 1
fi

# Affectation de variables pour affichage de version de CiviCRM
versionCIVI_WP=$(grep "define('CIVICRM_PLUGIN_VERSION'" $chemin_plugins_wordpress/civicrm/civicrm.php 2>/dev/null | awk -F"'" '{print $4}')
versionCIVI_DRUPAL=$(grep '<version_no>' $chemin_plugins_drupal/civicrm/xml/version.xml 2>/dev/null | awk -F">" '{print $2}' | awk -F"<" '{print $1}')
versionCIVI_STANDALONE=$(grep '<version_no>' $chemin_plugins_standalone/core/xml/version.xml 2>/dev/null | awk -F">" '{print $2}' | awk -F"<" '{print $1}')

# Affichage de la version de CiviCRM 
[ $cms_instance == "wordpress" ] && [ -e $chemin_plugins_wordpress/civicrm/civicrm.php ] && echo -e "La version actuelle de CiviCRM est : ${PURPLE}${versionCIVI_WP}${NC} avec ${PURPLE}Wordpress${NC}"
[ $cms_instance == "drupal" ] && [ -e $chemin_plugins_drupal/civicrm/xml/version.xml ] && echo -e "La version actuelle de CiviCRM est : ${PURPLE}${versionCIVI_DRUPAL} avec ${PURPLE}Drupal${NC}"
[ $cms_instance == "standalone" ] && [ -e $chemin_plugins_standalone/core/xml/version.xml ] && echo -e "La version actuelle de CiviCRM est : ${PURPLE}${versionCIVI_STANDALONE} en ${PURPLE}Standalone${NC}"

echo -e '\e[93m=============================================\033[0m';

# Récuperation de la dernière version de CiviCRM avec une commande Wordpress sur la testwpcivi
echo -e "${BLUE}[ INFO ]${NC} récupération de la derniere version stable disponible"
last_version=$(curl -s https://download.civicrm.org/release/ | sed -n 's|.*<a href="/release/\([^"]*\)">.*|\1|p' | sort -V | tail -n1);
cd $vhosts;

## Choix version Dernière / Prod personnalisée / Beta / Alpha
echo "Quelle version souhaitez-vous ?";
echo -e "Dernière version (d) : ${GREEN}$last_version${NC}";
echo "Personnalisée (p) ?";
echo "Beta (b) ?";
echo "Alpha (a) ?";
read civi_type_version


set_maintenance_mode $instance $cms_instance

## Choix version
case $civi_type_version in
        "d")
            civi_version="$last_version"

            if [[ $civi_version =~ ^[0-9]*.[0-9]*.[0-9]*$ ]]; then
                updateCivicrm civi_folder civi_version
            else
                echo -e '\e[93m=======================================\033[0m'
                echo -e '\e[93m\033[31m Ce n`est pas une version connue\033[31m'
                echo -e '\e[93m=======================================\033[0m'
                exit 1
            fi
            ;;

        "p")
            echo "Choisissez la version que vous souhaitez installer (X.YY.Z)  ?"
            read civi_version

            if [[ $civi_version =~ ^[0-9]*.[0-9]*.[0-9]*$ ]]; then
                updateCivicrm civi_folder civi_version
            else
                echo -e '\e[93m=======================================\033[0m'
                echo -e '\e[93m\033[31m Ce n`est pas une version connue\033[31m'
                echo -e '\e[93m=======================================\033[0m'
                exit 1
            fi
            ;; 

        "b")
            updateCivicrm civi_folder 
            ;;

        "a")
            updateCivicrm civi_folder
            ;;

		*)
			echo "Choix incorrect"
			;;
esac

cd $vhosts
unset_maintenance_mode $instance $cms_instance
