#!/bin/bash


if [ "$1" = "--cancel" ]; then
	exec wpdall --list "previous_wpall"
	exit $?
fi

if [ "$1" = "--list" ] && [ -n "$2" ]; then
	extensions=$(cat "$2")
else
	extensions=$(php -d memory_limit=512M $(which wp) --allow-root plugin list --status=inactive --format=csv --field=name)
fi

if [ -z "$extensions" ]; then
    echo -e "${BLUE}[ INFO ]${NC} Pas d'extension à activer"
    exit 0
fi

if [ -e "previous_wpall" ]; then
	rm  "previous_wpall"
fi

good_display()
{
    while read -r line; do
        if [[ "$line" =~ Warning:\ (.*) ]]; then
            local detail="${BASH_REMATCH[1]}"
            echo -e "${YELLOW}[ ATTENTION ]${NC} $detail"
            continue
        fi

        if [[ "$line" =~ \'(.*)\' ]]; then
            local plugin="${BASH_REMATCH[1]}"
            echo -e "${GREEN}[ SUCCÈS ]${NC} Activation de ${PURPLE}${plugin}${NC}"
            echo $plugin >> "previous_wpall"
            continue
        fi

        if [[ "$line" =~ Error:\ (.*) ]]; then
            local detail="${BASH_REMATCH[1]}"
            echo -e "${RED}[ ERREUR ]${NC} $detail"
            continue
        fi
    done
}
php -d memory_limit=512M $(which wp) --allow-root plugin activate $extensions | good_display
echo -e "${GREEN}[ SUCCÈS ]${NC} fini !"
