#!/bin/bash

if [ "$1" = "--cancel" ]; then
	exec wpall --list "previous_wpdall"
	exit $?
fi

if [ "$1" = "--list" ] && [ -n "$2" ]; then
	extensions=$(cat "$2")
else
	extensions=$(php -d memory_limit=512M $(which wp) --allow-root plugin list --status=active --format=csv --field=name)
fi

if [ -z "$extensions" ]; then
    echo -e "${BLUE}[ INFO ]${NC} Pas d'extension à désactiver"
    exit 0
fi

if [ -e "previous_wpdall" ]; then
	rm  "previous_wpdall"
fi

good_display()
{
    while read -r line; do
        if [[ "$line" =~ Warning:\ (.*) ]]; then
            local detail="${BASH_REMATCH[1]}"
            echo -e "${YELLOW}[ ATTENTION ]${NC} $detail"
            continue
        fi

        if [[ "$line" =~ \'(.*)\' ]]; then
            local plugin="${BASH_REMATCH[1]}"
            echo -e "${GREEN}[ SUCCÈS ]${NC} désactivation de ${PURPLE}${plugin}${NC}"
            echo "$plugin" >> "previous_wpdall"
            continue
        fi

        if [[ "$line" =~ Error:\ (.*) ]]; then
            local detail="${BASH_REMATCH[1]}"
            echo -e "${RED}[ ERREUR ]${NC} $detail"
            continue
        fi
    done
}
php -d memory_limit=512M $(which wp) --allow-root plugin deactivate $extensions | good_display
# echo -e "${GREEN}[ SUCCÈS ]$NC fini !"
